name:                ci-lang
version:             0.1.0.0
github:              "githubuser/ci-lang"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/caascade/ci-lang#readme>

dependencies:
- async
- base >= 4.7 && < 5
- bytestring
- classy-prelude
- conduit
- conduit-combinators
- containers
- deepseq
- directory
- docker
- filepath
- ghc-prim
- http-client
- lens
- mtl
- optparse-applicative
- process
- stm
- text
- transformers
- unix
- unordered-containers
- vector

library:
  source-dirs: src

executables:
  ci-lang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ci-lang

tests:
  ci-lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ci-lang
